const screenRoutes = {
  Home: 'Home',
  Profile: 'Profile',
  Rewards: 'Rewards',
  RewardHistory: 'RewardHistory',
  LeaderBoard: 'LeaderBoard',
  Login: 'Login',
  Community: 'Community',
  MarketPlace: 'MarketPlace',
  ForgotPassword: 'ForgotPassword',
  SignUp: 'SignUp',
  Wallet: 'Wallet',
  EarnCoin: 'EarnCoin',
  Search: 'Search',
  Language: 'Language',
  UploadContent: 'UploadContent',
  UploadContentSelect: 'UploadContentSelect',
  CreatorDashboard: 'CreatorDashboard',
  CreatorInsights: 'CreatorInsights',
  CreatorEarnings: 'CreatorEarnings',
  CreatorViews: 'CreatorViews',
  CreatorEngagement: 'CreatorEngagement',
  CreatorProfile: 'CreatorProfile',
  ReferAndEarn: 'ReferAndEarn',
  Settings: 'Settings',
  AddAccount: 'AddAccount',
  MyContent: 'MyAccount',
  CWebView: 'CWebView',
  Trade: 'Trade',
  SongDetail: 'SongDetail',
  MarketPlaceBuy: 'MarketPlaceBuy',
  MarketPlaceSell: 'MarketPlaceSell',
  AddFund: 'AddFund',
  PreSaleBuy: 'PreSaleBuy',
  PreSale: 'PreSale',
  WithdrawMoney: 'WithdrawMoney',
  CommunityChat: 'CommunityChat',
  EditProfile: 'EditProfile',
  CommunityGroup: 'CommunityGroup',
  Shorties: 'Shorties',
  StoryPost: 'StoryPost',
  GoInstaLive: 'GoInstaLive',
  ConsumerInstaLive: 'ConsumerInstaLive',
  AIAgent: 'AIAgent',
  AIGenerator: 'AIGenerator',
  AIVideoPlayer: 'AIVideoPlayer',
  AIHistory: 'AIHistory',
  VoiceRecord: 'VoiceRecord',
  SubscriptionScreen: 'SubscriptionScreen',
};

const stacks = {
  MainStack: 'MainStack',
  HomeStack: 'HomeStack',
  RootStack: 'RootStack',
};

const ROUTE_NAME = {...screenRoutes, ...stacks};

export default ROUTE_NAME;
